version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - '../:/app'
      - './nginx/conf.d:/etc/nginx/conf.d'
    ports:
      - '80:80'

  php:
    image: php:8.2-fpm-alpine
    volumes:
      - '../:/app'
