version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - '../:/app'
      - './nginx/conf.d:/etc/nginx/conf.d'
    ports:
      - '80:80'

  php:
    build:
      context: './php'
    volumes:
      - '../:/app'

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
